include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: true
    prefer_single_quotes: true
    prefer_final_locals: true
    avoid_global_state: true
    avoid_void_async: true
    prefer_const_constructors: true
    file_names: always_lower_case
    always_put_required_named_parameters_first: true
    always_specify_types: true
    avoid_function_literals_in_foreach_calls: true
    avoid_redundant_argument_values: true
    prefer_const_constructors_in_immutables: true
    avoid_unnecessary_containers: true
    prefer_explicit_local_variable_types: true
    always_use_package_imports: true
    lines_longer_than_80_chars: true
    prefer_function_declarations_over_variables: true

# Excluindo todas as classes geradas pelo freezed dentro de lib/domain/models/
analyzer:
  exclude:
    - lib/domain/models/**/*.dart