name: digprev_flutter
description: "Projeto de um aplicativo Flutter multiplataforma para o rastreamento da condição de saúde, 
              por meio de questionários que avaliam comportamento alimentar, hábitos alimentares, consumo 
              de ultraprocessados, qualidade da dieta, insatisfação corporal e sintomas de transtornos 
              alimentares."

publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.12.0
  go_router: ^14.8.0
  provider: ^6.1.2
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  cloud_firestore: ^5.6.4
  lucid_validation: ^1.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true