// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKk9g9PZcwiZXKuZrFV_Ol_Azg-6X-n0Q',
    appId: '1:980520351404:web:fc7888cfe509d336ee5109',
    messagingSenderId: '980520351404',
    projectId: 'prototipo-dig-prev',
    authDomain: 'prototipo-dig-prev.firebaseapp.com',
    storageBucket: 'prototipo-dig-prev.firebasestorage.app',
    measurementId: 'G-4MMQRTEVTW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKLvz17lzKpASQHXsEMHc4lSDF6gIiUdA',
    appId: '1:980520351404:android:31542b6da67b9ebeee5109',
    messagingSenderId: '980520351404',
    projectId: 'prototipo-dig-prev',
    storageBucket: 'prototipo-dig-prev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCG2HuQIBfHzLupk6l7p340JqACAhMc5wQ',
    appId: '1:980520351404:ios:c1758903bff66a1eee5109',
    messagingSenderId: '980520351404',
    projectId: 'prototipo-dig-prev',
    storageBucket: 'prototipo-dig-prev.firebasestorage.app',
    iosBundleId: 'com.ifgoiano.urt.digprevFlutter',
  );

}